### ISSUE TITLE
Django server timeout from HostOS browser

### ISSUE THREAD

**Issue by j99ht** [ging/fiware-idm-deprecated#13]
I have installed IDM in a VMWare virtual server.

From Firefox in VMWare server, I'm able to reach IDM GUI, Horizon has started with a internal IP address belonging to the domestic network (modifiying this in settings.py) (not using 127.0.0.1). However, from the Host or any other machine within the domestic network it is not possible to access Horizon (neither using an internet brower nor telnet to port 8000). http://ip:8000 is always timeout.

Using tcpdump, I'm able to see incoming traffic but not outgoing and ping is being answered by VMWare server.

Any idea about if Django is blocking external access? Horizon is configured as DEBUG, so not validation should be in place.

Thanks

**Comment by garcianavalon** [comment]
Hi,
I'll have to look into it because I don't know for sure what could be happening as you are the first one to have an issue like this. In my experience with other projects that used Django, if you are using the development server (running Horizon with fab horizon.dev_server or directly with sudo python tools/with_venv.sh python manage.py runserver) you have to make sure that Django listens to the correct IP address. 

Make sure that:
- You have redirected correctly your host port to the VM ports (for example host 8000 to vm 8000)
- Django is listening to 0.0.0.0:vm_port (tipically 8000). You can achive this using 
  - `fab horizon.dev_server:address='0.0.0.0:8000`
  - or
  - `sudo tools/with_venv.sh python manage.py runserver 0.0.0.0:8000`
- Now you should be able to connect to Horizon using http://host_ip:8000 (usually host_ip will be localhost)

Thats the only problems I can think of related to Django. If your issue persists check your VM settings and configuration and make sure its accessible from your host.

Cheers,
Enrique

**Comment by j99ht** [comment]
Thanks Enrique,

VM is accesible from my host and there are no port forwarding defined, VMware is taking care of this. 

I'll migrate to Apache following the production set up guide. Once set up is done, how should I run Horizon and Keystone?

Thanks

**Comment by garcianavalon** [comment]
Just follow the production set up guide http://fi-ware-idm.readthedocs.org/en/latest/setup/. It should be the same on a VM, as long as you have properly configured the network issues.

To run Keystone I recommend you to set it up as a service https://github.com/ging/keystone/wiki/Configure-as-service-guide

To run Horizon, just use Apache with mod_wsgi http://fi-ware-idm.readthedocs.org/en/latest/setup/#web-server-apache-mod_wsgi

Let me know if you find any issues.
Cheers.
