### ISSUE TITLE
Email signup not sent and " unsupported operand type(s) for +: 'NoneType' and 'str' " error

### ISSUE THREAD

**Issue by s209019** [ging/fiware-idm-deprecated#18]
Hi!
I have installed fiware-idm in a Ubuntu VM.

I had 2 problems:
--No mail is sent when i try to sign up, so i can't log in.

--When i log in using testing account,  an error occurs if i click on the "settings" button below the username label (top-right side)
![error](https://cloud.githubusercontent.com/assets/12278798/10373102/97c8f334-6deb-11e5-8557-fab172c051a6.png)

Here is the complete traceback:
https://drive.google.com/file/d/0B-ZtcVEe3SZNRzF2akJuNVhNR2M/view?usp=sharing

Which could be the reasons?
Thank you in advance.

**Comment by garcianavalon** [comment]
Hi!

The email not being sent could be because you haven't configured it properly. If you don't change the settings by default it will just print the email in your console. You can find how to set it up to send emails through an HTTP server here: http://fiware-idm.readthedocs.org/en/latest/setup.html#email-configuration.

The last error is a bug in the code, shame on me. I will upload a fix today.

**Comment by s209019** [comment]
Thank you very much!|

**Comment by garcianavalon** [comment]
The None Type error is fixed in https://github.com/ging/horizon/commit/55edf32723af76a019eefb1894948d8ab38629d3
