### ISSUE TITLE
[documentation] broken link in admin guide

### ISSUE THREAD

**Issue by ghost** [ging/fiware-idm-deprecated#26]
[Admin documentation](https://github.com/ging/fiware-idm/blob/master/doc/admin_guide.rst) points to this repository. [A fragment](https://github.com/ging/fiware-idm/blob/master/doc/admin_guide.rst#4-running-a-development-server) says not to use this settings for a production server, points to a link that [is broken](http://fiware-idm.readthedocs.org/en/latest/setup).

**Comment by garcianavalon** [comment]
fixed in 7a1229b50d4bc6af4c4d0d74e5bd6dd3a2bbe5a9
Thanks for the report :)

**Comment by ghost** [comment]
Thanks, so fast. Another issue, here? Broken link there:
http://fiware-idm.readthedocs.org/en/latest/setup.html#production-apache

You can find aditional help for setting up Keystone + MySQL here.
http://docs.openstack.org/havana/install-guide/install/apt/content/keystone-install.html -> http://docs.openstack.org/juno/install-guide/install/apt/content/keystone-install.html

**Comment by garcianavalon** [comment]
yeah, it looks like the link pointed to an old version is not supported anymore in the docs.
fixed in 92bfca023ddcb874614cccb0e8ae3ad18caaf190
Thanks again!

**Comment by ghost** [comment]
Next :)

not working:
http://fiware-idm.readthedocs.org/en/v4.4.1/oauth2
http://fiware-idm.readthedocs.org/en/latest/Oauth2.html

works:
http://fiware-idm.readthedocs.org/en/v4.4.0/oauth2

should be the same?

**Comment by garcianavalon** [comment]
haha thanks.

For v4.4.0 should be:
http://fiware-idm.readthedocs.org/en/v4.4.0/oauth2

For v4.4.1 and onwards should be:
http://fiware-idm.readthedocs.org/en/latest/oauth2.html (change latests with the version number)

There is a change due to switching from MarkDown to ReStructuredText for the documentation. Is there a place where the links are broken?

**Comment by ghost** [comment]
Ok, good to know

Now, how I get this broken links.
In google:
fiware idm oauth2

It is in third or forth position
https://www.google.es#q=fiware+idm+oauth2

you got:
http://fiware-idm.readthedocs.org/en/v4.4.0/oauth2/

from there, changing link manually, bad idea. But here is the broken link, "Read the docs" submenu and change version to 4.4.1 or latest. Is there a way to somehow redirect like this?

http://fiware-idm.readthedocs.org/en/v4.4.0/oauth2/ -> http://fiware-idm.readthedocs.org/en/v4.4.0/oauth2.html

the other broken part, from:
http://fiware-idm.readthedocs.org/en/v4.4.1/oauth2.html
http://fiware-idm.readthedocs.org/en/latest/oauth2.html

submenu, version, I cannot reach v4.4.0
http://fiware-idm.readthedocs.org/en/v4.4.0/oauth2.html

So it's just a integration. Could be possible? :)

**Comment by garcianavalon** [comment]
To be able to change from v4.4.0 version to others it would be requiered to configure some redirects due to the change in url structure. This is more of a read the docs issue, that generated the urls differently. I don't know if I can make those redirects somehow...

The integration is possible with versions greater than v4.4.1 and given the fact that v4.4.2 will come soon and v5 is on the makings, I'll rather just remove the v4.4.0 from read the docs :)

**Comment by ghost** [comment]
I think is not a good idea to destroy old documentation. One organization could continue using 4.4.0 and cannot upgrade due to its SLA's.

Is this useful for you in order to do redirection?
http://read-the-docs.readthedocs.org/en/latest/user-defined-redirects.html
http://read-the-docs.readthedocs.org/en/latest/automatic-redirects.html

**Comment by garcianavalon** [comment]
Yeah, looks useful. I'll take a look into it, thanks.
