### ISSUE TITLE
Problem with keystone.populate command

### ISSUE THREAD

**Issue by vmladenovic** [ging/fiware-idm-deprecated#30]
Hello,
I am trying to install Keystone and Horizon on Ubuntu 14.04 using your instructions. I am able to login using default user idm and to create an new application as well. But there is no applications client secret and id available anywhere (as it is case on FiwareLab instance). It must be some permission issues. Also when I try to execute 
    fab keystone.populate
I receive following errors:

  Created Services and Endpoints
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 743, in main
    _args, *_kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 424, in execute
    results['<local-only>'] = task.run(_args, *_new_kwargs)
  File "/home/idm/idm/deployment/keystone.py", line 362, in run
    self._create_endpoint_group_filters(keystone)
  File "/home/idm/idm/deployment/keystone.py", line 399, in _create_endpoint_group_filters
    regions = keystone.regions.list()
  File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 620, in __getattr__
    raise AttributeError("Unknown Attribute: %s" % name)
AttributeError: Unknown Attribute: regions

Also there is this error:
Checking Horizon...  Settings OK. INTERNAL_ROLES_IDS attribute could not be found. Please make sure you have completely installed Keystone before running this check.

I am really stuck, please help.
Tnx.

**Comment by ghost** [comment]
Hi,

I recommend you to use docker, and the docker of idm of bitergia
https://github.com/Bitergia/fiware-chanchan-docker/tree/master/images/idm-keyrock/4.3.0

If you don't want to use it, look at the scripts how all the things go on. Because there you have a working database out of the box with some default user and application registration (`default_provision.py`).

As said in [other issue](https://github.com/ging/fiware-idm/issues/15), bitergia idm should be integrated with this other docker image.

**Comment by garcianavalon** [comment]
Keystone.populate command is going to be removed in the next major release for a sql-alchemy migrate script https://github.com/ging/keystone/commit/afa092ad05c128d0180359e3ab71fae5acd9f591
