### ISSUE TITLE
OAuth2 token is not expiring

### ISSUE THREAD

**Issue by tevuore** [ging/fiware-idm-deprecated#53]
I'm using PEP Proxy with my own Keyrock installation. I noticed that with keystone token (pep-proxy keystone mode) tokens expire but not oauth2 tokens. 

I have used Password Credentials Grant and response from Keyrock has expires_in=3600 which is seconds. However I haven't seen token to expire ever. 

The URL PEP Proxy uses is <keystone_host>:<keystone_port>/v3/access-tokens/<token>.

Either
- problem in expiration
  - or problem in expires_in value

Regards,
-Tero

**Comment by federicofdez** [comment]
Hi @tevuore ,

After looking deeply into this issue, it turns out that there was indeed a problem when validating OAuth2 tokens. I just fixed this in https://github.com/ging/keystone/commit/b78fed76d6c22f97315b9d1fb31df1bb5082bae4, so that a `401 Unauthorized` error code is returned when the token has expired.

Everything should now work as expected, but please, feel free to reopen this issue if there is still anything not working properly.

Thank you very much for reporting this issue.

Regards,
Federico Fernández
