### ISSUE TITLE
Understanding workflow : mobile/web -> keyrock

### ISSUE THREAD

**Issue by grimabe** [ging/fiware-idm-deprecated#65]
Hi,

I am facing some issues when trying to use keyrock, so I am not sure I understand the workflow/architecture correctly.

In my case I have a mobile application as well as website where users can signup/signin and do actions of course (all api calls are made to a simple rest api).

I understand that using keyrock would bring a single entry point for authentication.

Here are the steps I followed to try it.
- I installed it with an image on the fiware-lab cloud.
- I logged in with the default idm account (idm/idm) on Horizon webpage (:8000)
- I registered an app called "test-app". (here I got the client_id / secret for this app)
- I used this credentials to make a POST request on :8000/oauth2/token

```
POST /oauth2/token HTTP/1.1
Host: myhost:8000
Authorization: Basic OGIzZjg2Y2EwYjE5NDFlODk1ZjA2MzcxYjJmZTMzYmQ6YmY1MGQ5MWE0YmU3NDcwYmIxMmIyMTExZWVlMmJlYzI=
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: 426d1b5e-2d1e-d46b-d105-57d102e06f53

grant_type=client_credentials

```

and I got the following response 

```
{
  "access_token": "EDB8UZaBbpFibUDBOu8baHXuvwmJ7q",
  "token_type": "Bearer",
  "expires_in": 3600
}
```

and then I tried to use this token to make calls on keystone API (port 5000) for example to create a user (http://developer.openstack.org/api-ref-identity-v3.html#createUser) :

```
POST /v3/users HTTP/1.1
Host: myhost:5000
Content-Type: application/json
X-Auth-Token: EDB8UZaBbpFibUDBOu8baHXuvwmJ7q
Cache-Control: no-cache
Postman-Token: 3532357e-56f8-3e1a-407d-21768d429a56

{
    "user": {
        "default_project_id": "263fd9",
        "description": "James Doe user",
        "domain_id": "1789d1",
        "email": "jdoe@example.com",
        "enabled": true,
        "name": "James Doe",
        "password": "secretsecret"
    }
}
```

 but for every call I made I got the following answer 

```
{
  "error": {
    "message": "The request you have made requires authentication.",
    "code": 401,
    "title": "Unauthorized"
  }
}
```

I was thinking doing this so that a user can just fill in a form in the mobile/web application and the mobile/web application will use its own credentials to get an access token and create the user on keyrock.

So I guess I have not the right token because I missed something in the flow or I am not using it the right way. 

I'll be happy to give more information if needed.

Thank you for your help

**Comment by federicofdez** [comment]
Hi @grimabe ,

The `X-Auth-Token` header needed in requests made to Keystone must actually be a **Keystone token**, not an **OAuth token**. To get a Keystone token, you need to make a POST request towards `$$keystone_address:port/v3/auth/tokens` (`$$keystone_address:port` would be your Keystone IP address and port), as you can see in [OpenStack docs](http://developer.openstack.org/api-ref-identity-v3.html#authenticate-v3). An example request using the credentials from `idm` account would be:

```
POST /v3/auth/tokens HTTP/1.1
Host: localhost:5000
Content-Type: application/json

{
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "id": "idm_user",
          "password": "idm"
        }
      }
    }
  }
}
```

You should get the Keystone token as response:

```
HTTP/1.1 201 Created
X-Subject-Token: d2bf4b2210f044fbb16554682353a969
Vary: X-Auth-Token
Content-Type: application/json
Content-Length: 1054
Date: Wed, 27 Apr 2016 13:24:54 GMT
```

You could now use this token in your user-creation request. However, note that **creating users through Keystone API requires an admin Keystone token**. This means that the token above will work since `idm_user` has been assigned the `admin` role before (this is done in KeyRock by default), but any other user account will have you run into the `401` error again.

Hope this helps! Don't hesitate to write back otherwise.

Cheers!

**Comment by grimabe** [comment]
Hi @federicofdez 

Your answer helped me a lot ! I am able to get the admin token and create users now.

Because I'am thinking to create users from a mobile app when they fill the sign up form I guess it is not safe and not the right way to use the admin account inside the mobile app in order to create users. 

What is your opinion about this ? what architecture should I follow ?

Thank you

**Comment by federicofdez** [comment]
Hi @grimabe ,

I've come up with these two options:
- You can either have your users register first in your KeyRock instance and, after that, ask for their credentials in your mobile app,
- or you can change the security policy in your KeyRock instance, so that no admin permissions are required to create users.

Please, let us know if we can be of further help.

Regards!

**Comment by federicofdez** [comment]
Seems to be solved. Feel free to open this issue again!

Cheers
