### ISSUE TITLE
Update XACML policies in AuthzForce from Keyrock

### ISSUE THREAD

**Issue by thomaskoeck** [ging/fiware-idm-deprecated#81]
Hi,

I am facing some difficulties at the moment. I want to create permissions and assign them to roles using REST calls. This works perfectly fine. However, the permissions that I create using the REST calls do not work as it looks to me that the XACML policies in Authzforce are not getting updated accordingly.

Is there a way to trigger KeyRock to update the XACML policies in Authzforce using REST calls? I would like to avoid the step of going to IdM - Application - Manage Roles - Save.

Thanks in advance.

Best regards,
Thomas

**Comment by federicofdez** [comment]
Hello @thomaskoeck ,

If you are to avoid the GUI of KeyRock when updating policies in Authzforce, you have to use directly the AuthZForce API, which is actually what the GUI does. I find the [documentation](http://authzforce-ce-fiware.readthedocs.io/en/release-5.4.1c/UserAndProgrammersGuide.html#adding-and-updating-policies) rather self-explanatory, but in case you have any doubts I think you'd better contact directly the AuthZForce team.

Hope this helps! Feel free to write back otherwise.

Regards,
Federico Fernández

**Comment by federicofdez** [comment]
I'm closing this issue now because of inactivity, but please feel free to reopen it we can be of further help!
